apiVersion: v1
kind: Service
metadata:
  name: ci-cd-canary-app-service
  labels:
    app: ci-cd-canary-app
spec:
  type: LoadBalancer
  selector:
    app: ci-cd-canary-app
    track: stable
  ports:
    - port: 80
      targetPort: 3000
